FEATURES_PROVIDED = \
    transceiver \
    periph_gpio \
    periph_uart \
    periph_spi \
    periph_i2c \
    periph_pwm \
    periph_adc \
    periph_rtc \
    periph_rtt \
    periph_random \
    periph_cpuid \
    cpp \
    #
